[package]
name = "Games"
version = "0.0.1"
published-at = "0x778ce991da269b80aa515c0e3c87db83afdca00458f4e4c40ea5d06d4f4c35aa"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
games = "0x0"
clock = "0x6"