[package]
name = "Games"
version = "0.0.1"
published-at = "0xd0b733ce4e693cbdbf29051c28a80d72f1f0148aeaeecd821c99d33065fc3dae"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
games = "0x0"
clock = "0x6"